### ISSUE TITLE
Select button to submit with

### ISSUE THREAD

**Issue by ericbrandwein** [hickford/MechanicalSoup#89]
Is there a way to select the button with which the browser submits the form?

**Comment by moy** [comment]
If you use `StatefulBrowser`, then `submit_selected` has a `btnName` argument: https://github.com/hickford/MechanicalSoup/blob/master/mechanicalsoup/stateful_browser.py#L112

Otherwise, look at [`Form.choose_submit`](https://github.com/hickford/MechanicalSoup/blob/master/mechanicalsoup/form.py#L111).

We don't really have a good doc (yet?), but testcases may help.

**Comment by moy** [comment]
Does the message above answer the question? If so, please close the bug or ask me to do so. If not, please clarify what you need.

**Comment by ericbrandwein** [comment]
Sorry, didn't see that you answered. It does answer my question, the problem I was having in fact was that the form used a multipart data encription type, which doesn't seem to be supported by this library. I opened an issue with this: https://github.com/hickford/MechanicalSoup/issues/90. Closing this one!
